### ISSUE TITLE
Three failed tests on i586 and armv7l in decoding_tests.CodecDecodeTests class

### ISSUE THREAD

**Issue by mcepl** [gmr/pamqp#11] opened 2018-09-09 21:38 UTC
Tests ``test_decode_by_type_long_long_data_type``, ``test_decode_embedded_value_long_long_data_type``, and ``test_decode_long_long_int_data_type`` fail on i586 and armv7l with the latest development version of OpenSUSE. I am not sure what's the unifying link between these two architectures (armv7l is 64bit, isn't it?), perhaps too small memory or something?

[build logs on i586](https://github.com/gmr/pamqp/files/2364681/python-pamqp_log.txt)
[build logs on armv7l](https://github.com/gmr/pamqp/files/2364683/python-pamqp_log.txt)

**Comment by scarabeusiv** [comment] 2018-09-11 07:27
Actually the issue is both of these are 32bit platforms, thus long long != int conversion there.

**Comment by gmr** [comment] 2018-09-11 14:18
The implications of supporting a 32-bit system are a bit interesting. The field type isn't actively used in AMQP as far as the core protocol/frames, so this failed test isn't indicating a major issue.

Most likely the data type is coming back as a long, but I believe the error is being raised by `Unittest.TestCase.assertEqual` complaining about type differences.

**Comment by gmr** [comment] 2018-09-11 17:33
I've updated the tests to address this (I think). It'd be great if you can test against master or 1.7 and let me know.

**Comment by gmr** [comment] 2018-09-20 14:10
Will close this. Feel to free open if the latest version didn't address this.

**Closed by gmr** 2018-09-20 14:10 UTC

**Comment by scarabeusiv** [comment] 2018-09-21 07:52
I can confirm the patch fixes the issue :)

**Comment by scarabeusiv** [comment] 2018-09-21 07:55
Actually with the 2.0 release one of the tests fail again:

```[   11s] ======================================================================
[   11s] FAIL: test_decode_embedded_value_long_uint_data_type (test_decoding.CodecDecodeTests)
[   11s] ----------------------------------------------------------------------
[   11s] Traceback (most recent call last):
[   11s]   File "/home/abuild/rpmbuild/BUILD/pamqp-2.0.0/tests/test_decoding.py", line 587, in test_decode_embedded_value_long_uint_data_type
[   11s]     self.assertIsInstance(decode._embedded_value(value)[1], int)
[   11s] AssertionError: 4294967295L is not an instance of <type 'int'>
```

**Comment by gmr** [comment] 2018-10-26 21:11
Python 2?

**Comment by mcepl** [comment] 2018-10-27 12:45
Yes, Python 2 only. The testsuite passes without problems on Python 3.7.
